# Generated by Django 5.2.4 on 2025-07-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_bnb_app', '0002_property_description_en_property_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.PositiveIntegerField(),
        ),
    ]
